version: '3'

services:
    myhotel-mysql-db:
        image: mysql:8.0
        container_name: myhotel-mysql-db
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: 123456
            MYSQL_USER: user
            MYSQL_PASSWORD: 123456
            MYSQL_ROOT_HOST: '%'
            MYSQL_DATABASE: myhotel-test